### ISSUE TITLE
Wiki for adding electrical machine using KubeJS not presently accurate

### ISSUE THREAD

**Issue by vinni57** [mikerooni/gtceu-modern-docs#36]
(copied from here: https://github.com/GregTechCEu/GregTech-Modern/issues/1822)

**GregTech CEu Version**

1.4.0-build_1029-SNAPSHOT

**Minecraft Version**

1.20.1

**Recipe Viewer Installed**

EMI

**Expected Behavior**

Wiki shows requirement for pollution production parameter in event.create().

Eg.

GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('test_electric', 'simple', **pollution_integer**, GTValues.LV, GTValues.MV, GTValues.HV)
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('test_recipe_type')
        .tankScalingFunction(tier => tier * 3200)
})

**Actual Behavior**

Wiki does not show such a requirement, instead having the following line:

event.create('test_electric', 'simple', GTValues.LV, GTValues.MV, GTValues.HV)

Following this results in the machine not generating a variant for the first GT power tier passed in.
Steps to Reproduce

Copied the example script for the production of a generator in startup scripts:

event.create('bio_generator', 'generator', GTValues.LV, GTValues.MV)
        .recipeTypes(['bio_generator'])
        .tankScalingFunction(tier => tier * 3200)

Here is the matching bio_generator recipe type:

event.create('bio_generator')
        .category('generator')
        .setEUIO('out')
        .setMaxIOSize(1, 0, 1, 0)
        .setSound(GTSoundEntries.CHEMICAL)

The resulting machine does not have an LV variant. Adding a 0 between 'generator' and GTValues.LV results in it working correctly, however

**Comment by AncientShotgun** [comment]
Pull request #37 should resolve this error in documentation.

**Comment by vinni57** [comment]
Sweet, thanks for the swift action!

**Comment by JuiceyBeans** [comment]
Issue can be closed (#37 got merged)
